/* Auto-generated by scripts/sync-data.js — do not edit by hand; edit data/*.json */
window.TRIP_DATA = {
  "meta": {
    "title": "Circus Vargas Goes to Japan",
    "docUrl": "https://docs.google.com/document/d/1t0yKSCdpAXDrOtdceFMqJ7ZXoe6zh-OmAR-z8jigMEA/edit",
    "lastSynced": "2026-09-25 09:48 PT",
    "partySize": "Chris, Adana, Amaya, Ellie, Robert, Sandra, Alyssa, Pete (8)",
    "timezone": "Asia/Tokyo",
    "tripStart": "2026-10-09",
    "tripEnd": "2026-10-18",
    "banner": "Shared edits happen in the Google Doc; checkmarks & stars on this phone only. No booking codes or ticket QR codes live on this public page."
  },
  "days": [
    {
      "id": "day-2026-10-09",
      "date": "2026-10-09",
      "weekday": "Friday",
      "title": "Arrive Tokyo — Haneda",
      "city": "Tokyo (Haneda)",
      "summary": "ANA NH125 lands Haneda ~9pm. Check in Villa Fontaine Premier (Terminal 3).",
      "callouts": [],
      "items": [
        {
          "id": "d9-flight",
          "type": "flight",
          "title": "ANA NH125 — land Haneda ~9pm",
          "detail": "Departs LAX Thu Oct 8 at 4:50pm (Terminal B) → arrives Haneda Fri Oct 9 at 9:00pm. Economy confirmed. E-ticket receipts are in email; mobile boarding passes come from ANA check-in (~24h before).",
          "status": "Booked",
          "mapsQuery": "Haneda Airport Terminal 3",
          "mapsUrl": null
        },
        {
          "id": "d9-hotel",
          "type": "stay",
          "title": "Villa Fontaine Premier Haneda Airport",
          "detail": "Night of Oct 9. 3 rooms, all with hot spring access: 1 Executive Twin (family of 4), 1 Deluxe Twin (Peter Fox), and 1 Deluxe Twin (Sandra & Robert Vargas). Booked.",
          "status": "Booked",
          "mapsQuery": "Villa Fontaine Premier Haneda Airport Terminal 3",
          "mapsUrl": null
        }
      ]
    },
    {
      "id": "day-2026-10-10",
      "date": "2026-10-10",
      "weekday": "Saturday",
      "title": "Haneda → Kyoto · City walk",
      "city": "Kyoto",
      "summary": "Jumbo van toward Tokyo Station, Nozomi 41 (2:30pm) to Kyoto, check in Hotel Forza Shijo Kawaramachi, then evening city walk if energy allows.",
      "callouts": [
        "Shinkansen is booked for 2:30pm (Nozomi 41) — later than the old mid-morning plan. Hotel Forza matches the Doc.",
        "Kansai Wide Area Pass recommended — watch: https://www.youtube.com/watch?v=Axqxa-FB73s"
      ],
      "items": [
        {
          "id": "d10-breakfast",
          "type": "food",
          "title": "Breakfast TBD",
          "detail": "Before departure from Haneda area.",
          "status": null,
          "mapsQuery": null,
          "mapsUrl": null
        },
        {
          "id": "d10-van",
          "type": "transit",
          "title": "Jumbo van Haneda → Shinagawa",
          "detail": "Prefer van with 8 + bags (not Keikyu). Aim to be at Tokyo Station well before the 2:30pm Nozomi.",
          "status": "Plan",
          "mapsQuery": "Tokyo Station",
          "mapsUrl": null
        },
        {
          "id": "d10-shinkansen",
          "type": "train",
          "title": "Nozomi 41 — Green Car",
          "detail": "Tokyo 14:30 → Kyoto 16:44. Green Car 8 · all 8 seats booked (SmartEX).",
          "status": "Booked",
          "mapsQuery": "Kyoto Station",
          "mapsUrl": null
        },
        {
          "id": "d10-hotel",
          "type": "stay",
          "title": "Hotel Forza Kyoto Shijo Kawaramachi",
          "detail": "Check-in after ~5pm arrival. 3 rooms booked.",
          "status": "Booked",
          "mapsQuery": "Hotel Forza Kyoto Shijo Kawaramachi",
          "mapsUrl": null
        },
        {
          "id": "d10-nishiki",
          "type": "place",
          "title": "Nishiki Market",
          "detail": "City walk from hotel area.",
          "status": null,
          "mapsQuery": "Nishiki Market Kyoto",
          "mapsUrl": "https://maps.app.goo.gl/pHPPsJyumXetHhQP9"
        },
        {
          "id": "d10-daishodo",
          "type": "place",
          "title": "Daishodo Woodblock Print Shop",
          "detail": null,
          "status": null,
          "mapsQuery": "Daishodo Woodblock Print Shop Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d10-yamatake",
          "type": "place",
          "title": "Yamatake Senpo fan shop",
          "detail": null,
          "status": null,
          "mapsQuery": "Yamatake Senpo Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d10-pontocho",
          "type": "place",
          "title": "Pontocho Alley / Geisha area",
          "detail": null,
          "status": null,
          "mapsQuery": "Pontocho Alley Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d10-gion",
          "type": "place",
          "title": "Shijo-kobashi → Gion",
          "detail": null,
          "status": null,
          "mapsQuery": "Gion Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d10-maruyama",
          "type": "place",
          "title": "Maruyama Park / Chion-in / Yasaka / Kodai-ji",
          "detail": null,
          "status": null,
          "mapsQuery": "Maruyama Park Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d10-hokanji",
          "type": "place",
          "title": "Hokanji (Yasaka Pagoda)",
          "detail": "A&P must see.",
          "status": null,
          "mapsQuery": "Yasaka Pagoda Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d10-hatsune",
          "type": "place",
          "title": "Hatsune Antiques",
          "detail": null,
          "status": null,
          "mapsQuery": "Hatsune Antiques Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d10-kiyomizu",
          "type": "place",
          "title": "Higashiyama / Kiyomizu-dera",
          "detail": null,
          "status": null,
          "mapsQuery": "Kiyomizu-dera Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d10-yogenin",
          "type": "place",
          "title": "Yogen-in Temple (blood ceilings)",
          "detail": "A&P must see.",
          "status": null,
          "mapsQuery": "Yogen-in Temple Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d10-kamo",
          "type": "place",
          "title": "Back via Kamo River / Takase Canal",
          "detail": null,
          "status": null,
          "mapsQuery": "Kamo River Kyoto",
          "mapsUrl": null
        }
      ]
    },
    {
      "id": "day-2026-10-11",
      "date": "2026-10-11",
      "weekday": "Sunday",
      "title": "Northwest Kyoto",
      "city": "Kyoto",
      "summary": "Nijo Castle, Golden Pavilion, Adashino/Otagi/Gioji temples, Arashiyama coffee & monkeys, optional Saihōji moss temple.",
      "callouts": [
        "Doc filled in Northwest Kyoto — long day; pick a realistic subset with kids.",
        "Saihōji (Kokedera) usually needs advance reservation."
      ],
      "items": [
        {
          "id": "d11-nijo",
          "type": "place",
          "title": "Nijo Castle",
          "detail": "Shogun palace with nightingale floors.",
          "status": null,
          "mapsQuery": "Nijo Castle Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d11-kura",
          "type": "place",
          "title": "Kura Daily Store",
          "detail": null,
          "status": null,
          "mapsQuery": "Kura Daily Store Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d11-kinkakuji",
          "type": "place",
          "title": "Kinkakuji (Golden Pavilion)",
          "detail": null,
          "status": null,
          "mapsQuery": "Kinkakuji Golden Pavilion Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d11-adashino",
          "type": "place",
          "title": "Adashino Nenbutsu-ji & Chikurin bamboo",
          "detail": "Similar vibe to Arashiyama bamboo, usually less crowded.",
          "status": null,
          "mapsQuery": "Adashino Nenbutsu-ji Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d11-sagano",
          "type": "place",
          "title": "Sagano Kobo paper shop",
          "detail": "Paper and souvenirs; Doc notes the shopkeeper.",
          "status": null,
          "mapsQuery": "Sagano Kobo Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d11-otagi",
          "type": "place",
          "title": "Otagi Nenbutsu-ji",
          "detail": "8th-century temple with 1,200+ stone rakan heads.",
          "status": null,
          "mapsQuery": "Otagi Nenbutsu-ji Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d11-gioji",
          "type": "place",
          "title": "Giōji Temple",
          "detail": "Moss and bamboo groves.",
          "status": null,
          "mapsQuery": "Gioji Temple Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d11-takao",
          "type": "food",
          "title": "√2 Riverside Takao Kyoto",
          "detail": "Riverside restaurant — a bit out of the way.",
          "status": null,
          "mapsQuery": "Riverside Takao Kyoto",
          "mapsUrl": null
        },
        {
          "id": "d11-arabica",
          "type": "food",
          "title": "% ARABICA Kyoto Arashiyama",
          "detail": "Riverfront coffee.",
          "status": null,
          "mapsQuery": "% ARABICA Kyoto Arashiyama",
          "mapsUrl": null
        },
        {
          "id": "d11-monkeys",
          "type": "place",
          "title": "Arashiyama Monkey Park Iwatayama",
          "detail": null,
          "status": null,
          "mapsQuery": "Arashiyama Monkey Park Iwatayama",
          "mapsUrl": null
        },
        {
          "id": "d11-saihoji",
          "type": "place",
          "title": "Saihōji (Kokedera) moss temple",
          "detail": "UNESCO site — usually needs advance booking.",
          "status": "Plan — reserve ahead",
          "mapsQuery": "Saihoji Kokedera Kyoto",
          "mapsUrl": null
        }
      ]
    },
    {
      "id": "day-2026-10-12",
      "date": "2026-10-12",
      "weekday": "Monday",
      "title": "Amanohashidate day trip",
      "city": "Amanohashidate",
      "summary": "JR Hashidate Limited Express (~2hr). Advance reservation. Snacks required — no food service.",
      "callouts": [
        "Videos: https://www.youtube.com/watch?v=A2iWvYmhFa8 and https://www.youtube.com/watch?v=kbtQYPlAh-A"
      ],
      "items": [
        {
          "id": "d12-train",
          "type": "train",
          "title": "JR Hashidate Limited Express",
          "detail": "~2hr. ADVANCE RESERVATION. No food service — bring snacks. Return to Kyoto same day.",
          "status": "Plan — reserve ahead",
          "mapsQuery": "Amanohashidate Station",
          "mapsUrl": null
        },
        {
          "id": "d12-crab",
          "type": "food",
          "title": "Seafood Atelier Hashidate Produce crab bento",
          "detail": "Alyssa priority.",
          "status": null,
          "mapsQuery": "Seafood Atelier Hashidate Produce",
          "mapsUrl": null
        },
        {
          "id": "d12-viewland",
          "type": "place",
          "title": "Viewland Park chairlift or funicular",
          "detail": "Pete must: chairlift. Safer for Ellie: funicular.",
          "status": null,
          "mapsQuery": "Amanohashidate Viewland",
          "mapsUrl": null
        },
        {
          "id": "d12-sandbar",
          "type": "place",
          "title": "Bike / walk sandbar ~3km",
          "detail": null,
          "status": null,
          "mapsQuery": "Amanohashidate sandbar",
          "mapsUrl": null
        },
        {
          "id": "d12-north-lift",
          "type": "place",
          "title": "Optional north-end chairlift",
          "detail": "Opposite-angle harbor view at the north end of the sandbar.",
          "status": null,
          "mapsQuery": "Amanohashidate north viewpoint chairlift",
          "mapsUrl": null
        },
        {
          "id": "d12-dinner",
          "type": "food",
          "title": "Dinner seafood TBD",
          "detail": "Then train back to Kyoto.",
          "status": null,
          "mapsQuery": "Amanohashidate seafood",
          "mapsUrl": null
        }
      ]
    },
    {
      "id": "day-2026-10-13",
      "date": "2026-10-13",
      "weekday": "Tuesday",
      "title": "A&P Nachi side quest · Kyoto TBD",
      "city": "Nachikatsuura / Kyoto",
      "summary": "A&P: Nachikatsuura / Nachi Falls mid/late morning. Rest of party TBD in Kyoto.",
      "callouts": [],
      "items": [
        {
          "id": "d13-nachi",
          "type": "place",
          "title": "Nachikatsuura / Nachi Falls (A&P)",
          "detail": "Mid/late morning. A&P reconnect evening Oct 14 after return.",
          "status": null,
          "mapsQuery": "Nachi Falls",
          "mapsUrl": null
        },
        {
          "id": "d13-kyoto",
          "type": "note",
          "title": "Rest of party — Kyoto TBD",
          "detail": "Coordinate in the Google Doc.",
          "status": null,
          "mapsQuery": "Kyoto",
          "mapsUrl": null
        }
      ]
    },
    {
      "id": "day-2026-10-14",
      "date": "2026-10-14",
      "weekday": "Wednesday",
      "title": "Kyoto → Tokyo Ginza",
      "city": "Tokyo (Ginza)",
      "summary": "Checkout Forza 11am. Nozomi 20 Kyoto 13:01 → Tokyo 15:15. Check in Koko Hotel Ginza (3pm).",
      "callouts": [],
      "items": [
        {
          "id": "d14-checkout",
          "type": "stay",
          "title": "Checkout Hotel Forza Kyoto Shijo Kawaramachi",
          "detail": "Checkout 11am.",
          "status": "Booked",
          "mapsQuery": "Hotel Forza Kyoto Shijo Kawaramachi",
          "mapsUrl": null
        },
        {
          "id": "d14-shinkansen",
          "type": "train",
          "title": "Nozomi 20 — Green Car",
          "detail": "Kyoto 13:01 → Tokyo 15:15. Green Car 8 · 6 seats booked so far (4 adults + 2 children). Two adults still need tickets.",
          "status": "Booked (6 of 8)",
          "mapsQuery": "Tokyo Station",
          "mapsUrl": null
        },
        {
          "id": "d14-hotel",
          "type": "stay",
          "title": "Koko Hotel Ginza 1-chome",
          "detail": "Check-in 3pm. Booked (Ginza 1-9-5 area).",
          "status": "Booked",
          "mapsQuery": "Koko Hotel Ginza 1-chome",
          "mapsUrl": null
        },
        {
          "id": "d14-reconnect",
          "type": "note",
          "title": "A&P reconnect evening",
          "detail": "After Nachi side quest.",
          "status": null,
          "mapsQuery": null,
          "mapsUrl": null
        }
      ]
    },
    {
      "id": "day-2026-10-15",
      "date": "2026-10-15",
      "weekday": "Thursday",
      "title": "Akihabara · Asakusa · Skytree",
      "city": "Tokyo",
      "summary": "Akihabara / Taito / Asakusa / Skytree loop — games, food, knives, views.",
      "callouts": [],
      "items": [
        {
          "id": "d15-akihabara",
          "type": "place",
          "title": "Akihabara — games / gachapon",
          "detail": "Pete picks up items for Marco; also gachapon.",
          "status": null,
          "mapsQuery": "Akihabara Tokyo",
          "mapsUrl": null
        },
        {
          "id": "d15-kappabashi",
          "type": "place",
          "title": "Kappabashi",
          "detail": "Kitchen street.",
          "status": null,
          "mapsQuery": "Kappabashi Tokyo",
          "mapsUrl": null
        },
        {
          "id": "d15-seive",
          "type": "food",
          "title": "Seive Matcha",
          "detail": null,
          "status": null,
          "mapsQuery": "Seive Matcha Tokyo",
          "mapsUrl": null
        },
        {
          "id": "d15-melon",
          "type": "food",
          "title": "Asakusa Kagetsudō Melon Bread",
          "detail": null,
          "status": null,
          "mapsQuery": "Kagetsudo Melon Bread Asakusa",
          "mapsUrl": null
        },
        {
          "id": "d15-zaku",
          "type": "place",
          "title": "Zaku Knives",
          "detail": "https://zakuknives.com/",
          "status": null,
          "mapsQuery": "Zaku Knives Tokyo",
          "mapsUrl": null,
          "link": "https://zakuknives.com/"
        },
        {
          "id": "d15-kimono",
          "type": "place",
          "title": "Kimono Reborn Tokyo",
          "detail": null,
          "status": null,
          "mapsQuery": "Kimono Reborn Tokyo",
          "mapsUrl": null
        },
        {
          "id": "d15-origami",
          "type": "place",
          "title": "Tokyo Origami Museum?",
          "detail": "Optional / confirm.",
          "status": null,
          "mapsQuery": "Tokyo Origami Museum",
          "mapsUrl": null
        },
        {
          "id": "d15-skytree",
          "type": "place",
          "title": "Skytree area",
          "detail": null,
          "status": null,
          "mapsQuery": "Tokyo Skytree",
          "mapsUrl": null
        },
        {
          "id": "d15-pizza",
          "type": "food",
          "title": "Parazzo San Gusto pizza?",
          "detail": "Optional.",
          "status": null,
          "mapsQuery": "Parazzo San Gusto Tokyo",
          "mapsUrl": null
        }
      ]
    },
    {
      "id": "day-2026-10-16",
      "date": "2026-10-16",
      "weekday": "Friday",
      "title": "Mom's birthday! Akasaka / Shinjuku / Shibuya",
      "city": "Tokyo",
      "summary": "Birthday day — Imperial Palace, Harry Potter shop, Samurai Museum, Omoide Yokocho, Takeshita, cameras, tacos, Donki, ramen, Shibuya night view.",
      "callouts": [
        "Happy birthday, Mom!"
      ],
      "items": [
        {
          "id": "d16-palace",
          "type": "place",
          "title": "Imperial Palace",
          "detail": null,
          "status": null,
          "mapsQuery": "Imperial Palace Tokyo",
          "mapsUrl": null
        },
        {
          "id": "d16-harry-potter",
          "type": "place",
          "title": "Harry Potter Shop",
          "detail": "From the Doc — confirm which location before going.",
          "status": null,
          "mapsQuery": "Harry Potter Shop Tokyo",
          "mapsUrl": null
        },
        {
          "id": "d16-samurai",
          "type": "place",
          "title": "Samurai Museum (A&P)",
          "detail": null,
          "status": null,
          "mapsQuery": "Samurai Museum Shinjuku",
          "mapsUrl": null
        },
        {
          "id": "d16-godzilla",
          "type": "place",
          "title": "Godzilla Head",
          "detail": "Shinjuku.",
          "status": null,
          "mapsQuery": "Godzilla Head Shinjuku",
          "mapsUrl": null
        },
        {
          "id": "d16-omoide",
          "type": "place",
          "title": "Omoide Yokocho (Memory Lane)",
          "detail": "Landmark alley of food stalls for simple fare.",
          "status": null,
          "mapsQuery": "Omoide Yokocho Shinjuku",
          "mapsUrl": null
        },
        {
          "id": "d16-camera",
          "type": "place",
          "title": "Used Camera Box / Tokyo Used Camera",
          "detail": null,
          "status": null,
          "mapsQuery": "Tokyo Used Camera",
          "mapsUrl": null
        },
        {
          "id": "d16-takeshita",
          "type": "place",
          "title": "Takeshita Street",
          "detail": "Harajuku.",
          "status": null,
          "mapsQuery": "Takeshita Street Harajuku",
          "mapsUrl": null
        },
        {
          "id": "d16-tacos",
          "type": "food",
          "title": "Tacos 3 Hermanos",
          "detail": null,
          "status": null,
          "mapsQuery": "Tacos 3 Hermanos Tokyo",
          "mapsUrl": null
        },
        {
          "id": "d16-cola",
          "type": "food",
          "title": "Iyoshi Cola",
          "detail": null,
          "status": null,
          "mapsQuery": "Iyoshi Cola Tokyo",
          "mapsUrl": null
        },
        {
          "id": "d16-donki",
          "type": "place",
          "title": "Don Quijote Mega",
          "detail": null,
          "status": null,
          "mapsQuery": "Don Quijote Mega Shinjuku",
          "mapsUrl": null
        },
        {
          "id": "d16-ramen",
          "type": "food",
          "title": "Ramen family dinner TBD",
          "detail": "Maybe Shojin vegetarian ramen.",
          "status": null,
          "mapsQuery": "Shojin Tokyo ramen",
          "mapsUrl": null
        },
        {
          "id": "d16-shibuya",
          "type": "place",
          "title": "Shibuya Crossing / Hikarie Sky Lobby",
          "detail": "Night view.",
          "status": null,
          "mapsQuery": "Shibuya Hikarie Sky Lobby",
          "mapsUrl": null
        }
      ]
    },
    {
      "id": "day-2026-10-17",
      "date": "2026-10-17",
      "weekday": "Saturday",
      "title": "Enoshima / Kamakura day trip",
      "city": "Enoshima",
      "summary": "Tokyo/Yurakucho → Ofuna → Shonan Monorail (~90min). Sea Candle, caves, optional Enoden.",
      "callouts": [],
      "items": [
        {
          "id": "d17-transit",
          "type": "transit",
          "title": "Tokyo / Yurakucho → Ofuna → Shonan Monorail",
          "detail": "~90 minutes to Enoshima.",
          "status": "Plan",
          "mapsQuery": "Enoshima Station Shonan Monorail",
          "mapsUrl": null
        },
        {
          "id": "d17-cave",
          "type": "place",
          "title": "Enoshima Iwaya Cave via Sea Candle",
          "detail": null,
          "status": null,
          "mapsQuery": "Enoshima Iwaya Cave",
          "mapsUrl": null
        },
        {
          "id": "d17-enoden",
          "type": "train",
          "title": "Optional Enoshima Electric Railway",
          "detail": null,
          "status": null,
          "mapsQuery": "Enoshima Electric Railway",
          "mapsUrl": null
        },
        {
          "id": "d17-sasuke",
          "type": "place",
          "title": "Sasuke Inari (fox shrine)",
          "detail": "Try if time.",
          "status": null,
          "mapsQuery": "Sasuke Inari Shrine Kamakura",
          "mapsUrl": null
        }
      ]
    },
    {
      "id": "day-2026-10-18",
      "date": "2026-10-18",
      "weekday": "Sunday",
      "title": "Homeward — Haneda → LAX",
      "city": "Tokyo (Haneda)",
      "summary": "Checkout Ginza, head to Haneda. Return flight ~9pm HND → LAX 3:10pm.",
      "callouts": [],
      "items": [
        {
          "id": "d18-checkout",
          "type": "stay",
          "title": "Checkout Koko Hotel Ginza",
          "detail": "Checkout 11am. Luggage plan TBD.",
          "status": "Booked",
          "mapsQuery": "Koko Hotel Ginza 1-chome",
          "mapsUrl": null
        },
        {
          "id": "d18-flight",
          "type": "flight",
          "title": "ANA NH126 — Haneda → LAX",
          "detail": "Departs Haneda Sun Oct 18 at 9:05pm (Terminal 2) → arrives LAX 3:10pm same calendar day. Economy confirmed. Boarding passes via ANA check-in closer to departure.",
          "status": "Booked",
          "mapsQuery": "Haneda Airport",
          "mapsUrl": null
        }
      ]
    }
  ],
  "stays": [
    {
      "id": "stay-haneda",
      "name": "Villa Fontaine Premier Haneda Airport",
      "area": "Haneda Airport Terminal 3",
      "nights": "Oct 9",
      "checkIn": "evening (after ~9pm arrival)",
      "checkOut": "morning Oct 10",
      "status": "Booked",
      "mapsQuery": "Villa Fontaine Premier Haneda Airport Terminal 3",
      "mapsUrl": null,
      "notes": "3 rooms, all with hot spring access: 1 Executive Twin (Christopher Vargas, family of 4), 1 Deluxe Twin (Peter Fox), and 1 Deluxe Twin (Sandra & Robert Vargas). Connected to Terminal 3. Leave mid-morning for Tokyo Station / Nozomi 41."
    },
    {
      "id": "stay-kyoto",
      "name": "Hotel Forza Kyoto Shijo Kawaramachi",
      "area": "Kyoto — Shijo Kawaramachi",
      "nights": "Oct 10–14",
      "checkIn": "after Nozomi arrival (~5pm)",
      "checkOut": "11:00am",
      "status": "Booked",
      "mapsQuery": "Hotel Forza Kyoto Shijo Kawaramachi",
      "mapsUrl": null,
      "notes": "Confirmed under Sandra Vargas: 2 Superior Double + 1 Casual Triple (3 rooms)."
    },
    {
      "id": "stay-ginza",
      "name": "Koko Hotel Ginza 1-chome",
      "area": "Tokyo — Ginza",
      "nights": "Oct 14–18",
      "checkIn": "3:00pm",
      "checkOut": "11:00am",
      "status": "Booked",
      "mapsQuery": "Koko Hotel Ginza 1-chome",
      "mapsUrl": null,
      "notes": "Ginza 1-9-5 area. At least one Superior Twin held for the family with kids; other rooms may be separate bookings. Arrive after Nozomi 20 (~3:15pm Tokyo)."
    }
  ],
  "trains": [
    {
      "id": "train-nozomi-41",
      "label": "Outbound Shinkansen — Nozomi 41",
      "date": "2026-10-10",
      "from": "Tokyo 14:30",
      "to": "Kyoto 16:44",
      "car": "Green Car 8 — 8 reserved seats",
      "status": "Booked",
      "notes": "All 8 seats held (SmartEX). Leave Haneda with time for Tokyo Station boarding. QR tickets live in the SmartEX app — not on this public page."
    },
    {
      "id": "train-nozomi-20",
      "label": "Return Shinkansen — Nozomi 20",
      "date": "2026-10-14",
      "from": "Kyoto 13:01",
      "to": "Tokyo 15:15",
      "car": "Green Car 8 — 6 reserved seats so far",
      "status": "Booked (6 of 8)",
      "notes": "Confirms 4 adults + 2 children. Two adults still need return seats. Still lands before Ginza 3pm check-in."
    },
    {
      "id": "train-hashidate",
      "label": "JR Hashidate Limited Express (Amanohashidate)",
      "date": "2026-10-12",
      "from": "Kyoto",
      "to": "Amanohashidate (~2hr)",
      "car": "Advance reservation required",
      "status": "Plan — reserve ahead",
      "notes": "No food service — bring snacks. Return same day to Kyoto."
    },
    {
      "id": "train-enoshima",
      "label": "Enoshima / Kamakura day trip",
      "date": "2026-10-17",
      "from": "Tokyo / Yurakucho → Ofuna",
      "to": "Shonan Monorail → Enoshima (~90min total)",
      "car": "Local + monorail",
      "status": "Plan",
      "notes": "Optional Enoshima Electric Railway."
    }
  ],
  "phrases": {
    "pronunciationTip": "Japanese vowels are pure and short: a (ah), i (ee), u (oo), e (eh), o (oh). Give each syllable even stress. Pitch accent matters more than English-style stress — listen and mimic.",
    "categories": [
      {
        "id": "greetings",
        "name": "Greetings & courtesy",
        "items": [
          {
            "id": "p-ohayo",
            "ja": "おはようございます",
            "romaji": "ohayō gozaimasu",
            "en": "Good morning"
          },
          {
            "id": "p-konnichiwa",
            "ja": "こんにちは",
            "romaji": "konnichiwa",
            "en": "Hello / Good afternoon"
          },
          {
            "id": "p-konbanwa",
            "ja": "こんばんは",
            "romaji": "konbanwa",
            "en": "Good evening"
          },
          {
            "id": "p-sayonara",
            "ja": "さようなら",
            "romaji": "sayōnara",
            "en": "Goodbye"
          },
          {
            "id": "p-arigato",
            "ja": "ありがとうございます",
            "romaji": "arigatō gozaimasu",
            "en": "Thank you (polite)"
          },
          {
            "id": "p-sumimasen",
            "ja": "すみません",
            "romaji": "sumimasen",
            "en": "Excuse me / Sorry"
          },
          {
            "id": "p-hajimemashite",
            "ja": "はじめまして",
            "romaji": "hajimemashite",
            "en": "Nice to meet you"
          },
          {
            "id": "p-hai",
            "ja": "はい",
            "romaji": "hai",
            "en": "Yes"
          },
          {
            "id": "p-ie",
            "ja": "いいえ",
            "romaji": "iie (“ee-eh”)",
            "en": "No"
          },
          {
            "id": "p-daijobu",
            "ja": "大丈夫です",
            "romaji": "daijōbu desu",
            "en": "I'm fine / It's okay"
          },
          {
            "id": "p-onegai",
            "ja": "お願いします",
            "romaji": "onegai shimasu",
            "en": "Please (request)"
          },
          {
            "id": "p-dozo",
            "ja": "どうぞ",
            "romaji": "dōzo",
            "en": "Please (go ahead / here you are)"
          },
          {
            "id": "p-ogenki",
            "ja": "お元気ですか",
            "romaji": "ogenki desu ka",
            "en": "How are you?"
          }
        ]
      },
      {
        "id": "getting-around",
        "name": "Getting around",
        "items": [
          {
            "id": "p-wa-doko",
            "ja": "…はどこですか",
            "romaji": "… wa doko desu ka",
            "en": "Where is …?"
          },
          {
            "id": "p-eki",
            "ja": "駅はどこですか",
            "romaji": "eki wa doko desu ka",
            "en": "Where is the station?"
          },
          {
            "id": "p-densha",
            "ja": "この電車は…に行きますか",
            "romaji": "kono densha wa … ni ikimasu ka",
            "en": "Does this train go to …?"
          },
          {
            "id": "p-kippu",
            "ja": "切符をください",
            "romaji": "kippu o kudasai",
            "en": "A ticket, please"
          },
          {
            "id": "p-ikura-train",
            "ja": "いくらですか",
            "romaji": "ikura desu ka",
            "en": "How much is it?"
          },
          {
            "id": "p-norikae",
            "ja": "乗り換えはどこですか",
            "romaji": "norikae wa doko desu ka",
            "en": "Where do I transfer?"
          },
          {
            "id": "p-basutei",
            "ja": "バス停はどこですか",
            "romaji": "basutei wa doko desu ka",
            "en": "Where is the bus stop?"
          },
          {
            "id": "p-chizu",
            "ja": "地図を見せてください",
            "romaji": "chizu o misete kudasai",
            "en": "Please show me a map"
          },
          {
            "id": "p-orimasu",
            "ja": "ここで降ります",
            "romaji": "koko de orimasu",
            "en": "I'm getting off here"
          },
          {
            "id": "p-toire",
            "ja": "トイレはどこですか",
            "romaji": "toire wa doko desu ka",
            "en": "Where is the restroom?"
          }
        ]
      },
      {
        "id": "eating",
        "name": "Eating",
        "items": [
          {
            "id": "p-menu",
            "ja": "メニューをください",
            "romaji": "menyū o kudasai",
            "en": "Menu, please"
          },
          {
            "id": "p-osusume",
            "ja": "おすすめは何ですか",
            "romaji": "osusume wa nan desu ka",
            "en": "What do you recommend?"
          },
          {
            "id": "p-arimasu",
            "ja": "…はありますか",
            "romaji": "… wa arimasu ka",
            "en": "Do you have …?"
          },
          {
            "id": "p-veg",
            "ja": "ペスカタリアンです",
            "romaji": "pesukatarian desu",
            "en": "I'm a pescatarian"
          },
          {
            "id": "p-omizu",
            "ja": "お水をください",
            "romaji": "omizu o kudasai",
            "en": "Water, please"
          },
          {
            "id": "p-kore-des",
            "ja": "これをください",
            "romaji": "kore o kudasai",
            "en": "This one, please"
          },
          {
            "id": "p-itadakimasu",
            "ja": "いただきます",
            "romaji": "itadakimasu",
            "en": "Let's eat (before meal)"
          },
          {
            "id": "p-gochisosama",
            "ja": "ごちそうさまでした",
            "romaji": "gochisōsama deshita",
            "en": "Thank you for the meal"
          },
          {
            "id": "p-betsubetsu",
            "ja": "別々でお願いします",
            "romaji": "betsubetsu de onegai shimasu",
            "en": "Separate checks, please"
          },
          {
            "id": "p-okaikei",
            "ja": "お会計をお願いします",
            "romaji": "okaikei o onegai shimasu",
            "en": "Check, please"
          },
          {
            "id": "p-oishii",
            "ja": "おいしいです",
            "romaji": "oishii desu",
            "en": "It's delicious"
          },
          {
            "id": "p-oishikatta",
            "ja": "おいしかったです",
            "romaji": "oishikatta desu",
            "en": "It was delicious (past / more formal)"
          }
        ]
      },
      {
        "id": "shopping",
        "name": "Shopping",
        "items": [
          {
            "id": "p-ikura-shop",
            "ja": "いくらですか",
            "romaji": "ikura desu ka",
            "en": "How much is it?"
          },
          {
            "id": "p-kore-kudasai",
            "ja": "これをください",
            "romaji": "kore o kudasai",
            "en": "I'll take this"
          },
          {
            "id": "p-card",
            "ja": "クレジットカードは使えますか",
            "romaji": "kurejitto kādo wa tsukaemasu ka",
            "en": "Can I use a credit card?"
          },
          {
            "id": "p-genkin",
            "ja": "現金",
            "romaji": "genkin",
            "en": "Cash"
          },
          {
            "id": "p-misete",
            "ja": "見せてください",
            "romaji": "misete kudasai",
            "en": "Please show me"
          },
          {
            "id": "p-ikko",
            "ja": "一個ください",
            "romaji": "ikko kudasai",
            "en": "One, please"
          },
          {
            "id": "p-menzei",
            "ja": "免税できますか",
            "romaji": "menzei dekimasu ka",
            "en": "Can I get tax-free?"
          },
          {
            "id": "p-fukuro",
            "ja": "袋は要りますか",
            "romaji": "fukuro wa irimasu ka",
            "en": "Do you need a bag?"
          },
          {
            "id": "p-atatame",
            "ja": "温めますか",
            "romaji": "atatamemasu ka",
            "en": "Shall I warm it up?"
          }
        ]
      },
      {
        "id": "hotels",
        "name": "Hotels & airports",
        "items": [
          {
            "id": "p-yoyaku",
            "ja": "予約しています",
            "romaji": "yoyaku shiteimasu",
            "en": "I have a reservation"
          },
          {
            "id": "p-checkin",
            "ja": "チェックインをお願いします",
            "romaji": "chekkuin o onegai shimasu",
            "en": "Check-in, please"
          },
          {
            "id": "p-passport",
            "ja": "パスポートでいいですか",
            "romaji": "pasupōto de ii desu ka",
            "en": "Is a passport OK?"
          },
          {
            "id": "p-choshoku",
            "ja": "朝食は何時ですか",
            "romaji": "chōshoku wa nanji desu ka",
            "en": "What time is breakfast?"
          },
          {
            "id": "p-wifi",
            "ja": "Wi-Fiはありますか",
            "romaji": "waifai wa arimasu ka",
            "en": "Is there Wi-Fi?"
          },
          {
            "id": "p-nimotsu",
            "ja": "荷物を預けてもいいですか",
            "romaji": "nimotsu o azukete mo ii desu ka",
            "en": "May I leave my luggage?"
          },
          {
            "id": "p-eigo",
            "ja": "英語は分かりますか？",
            "romaji": "Eigo wa wakarimasu ka?",
            "en": "Do you understand English?"
          },
          {
            "id": "p-yoku-wakarimasen",
            "ja": "よく分かりません",
            "romaji": "Yoku wakarimasen",
            "en": "I don't understand well"
          }
        ]
      },
      {
        "id": "emergencies",
        "name": "Emergencies",
        "items": [
          {
            "id": "p-tasukete",
            "ja": "助けてください",
            "romaji": "tasukete kudasai",
            "en": "Please help me"
          },
          {
            "id": "p-byoin",
            "ja": "病院はどこですか",
            "romaji": "byōin wa doko desu ka",
            "en": "Where is the hospital?"
          },
          {
            "id": "p-yakkyoku",
            "ja": "薬局はどこですか",
            "romaji": "yakkyoku wa doko desu ka",
            "en": "Where is the pharmacy?"
          },
          {
            "id": "p-keisatsu",
            "ja": "警察を呼んでください",
            "romaji": "keisatsu o yonde kudasai",
            "en": "Please call the police"
          },
          {
            "id": "p-mayoimashita",
            "ja": "道に迷いました",
            "romaji": "michi ni mayoimashita",
            "en": "I'm lost"
          },
          {
            "id": "p-nakushimashita",
            "ja": "…をなくしました",
            "romaji": "… o nakushimashita",
            "en": "I lost …"
          },
          {
            "id": "p-119",
            "ja": "119番",
            "romaji": "hyaku-jū-kyū ban (119)",
            "en": "Ambulance / fire"
          },
          {
            "id": "p-110",
            "ja": "110番",
            "romaji": "hyaku-tō ban (110)",
            "en": "Police"
          }
        ]
      }
    ]
  },
  "links": {
    "doc": "https://docs.google.com/document/d/1t0yKSCdpAXDrOtdceFMqJ7ZXoe6zh-OmAR-z8jigMEA/edit",
    "kansaiPassVideo": "https://www.youtube.com/watch?v=Axqxa-FB73s",
    "amanohashidateVideo1": "https://www.youtube.com/watch?v=A2iWvYmhFa8",
    "amanohashidateVideo2": "https://www.youtube.com/watch?v=kbtQYPlAh-A",
    "zakuKnives": "https://zakuknives.com/",
    "nishikiMaps": "https://maps.app.goo.gl/pHPPsJyumXetHhQP9",
    "washletGuide": "https://cotoacademy.com/guide-japanese-toilets-japanese-toilet-buttons-infographic/",
    "washletVideo": "https://youtu.be/QabwDks5ETA"
  },
  "party": {
    "party": "Chris, Adana, Amaya, Ellie, Robert, Sandra, Alyssa, and Pete — 8 people (6 adults, Amaya ~10, Ellie ~23 months on the trip).",
    "members": [
      "Chris",
      "Adana",
      "Amaya",
      "Ellie",
      "Robert",
      "Sandra",
      "Alyssa",
      "Pete"
    ],
    "notes": [
      "Shared itinerary lives in the Google Doc — edit there so everyone sees updates.",
      "This phone app stores done/visited, stars, and personal notes in localStorage only (per device).",
      "Flights: Land Haneda ~9pm Oct 9; home Haneda ~9pm Oct 18 → LAX 3:10pm.",
      "Prefer jumbo van Haneda→Shinagawa morning of Oct 10 (not Keikyu with 8 + bags).",
      "Shinkansen: outbound Nozomi 41 is fully booked (8 Green Car seats); return Nozomi 20 has 6 of 8 Green Car seats booked — 2 adults still need tickets.",
      "A&P side quests: Nachi Falls (Oct 13), Samurai Museum (Oct 16), Yasaka Pagoda & Yogen-in (Oct 10).",
      "Mom's birthday Oct 16 — celebrate in Shinjuku/Shibuya!",
      "No passport numbers or payment cards in this public site."
    ],
    "priorities": [
      {
        "who": "Alyssa",
        "what": "Seafood Atelier Hashidate crab bento; confirm Forza→Shijo Kawaramachi doc note"
      },
      {
        "who": "Pete",
        "what": "Viewland chairlift; Samurai Museum; Yasaka Pagoda & Yogen-in"
      },
      {
        "who": "Amaya",
        "what": "Akihabara games / gachapon"
      },
      {
        "who": "Ellie",
        "what": "Prefer funicular over chairlift at Viewland when possible"
      },
      {
        "who": "Mom",
        "what": "Birthday day Oct 16 — Shinjuku/Shibuya celebration"
      }
    ]
  },
  "photos": {
    "Haneda Airport Terminal 3": {
      "file": "images/haneda-airport-terminal-3.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Haneda Airport",
      "pageTitle": "Haneda Airport",
      "pageUrl": "https://en.wikipedia.org/wiki/Haneda_Airport"
    },
    "Villa Fontaine Premier Haneda Airport Terminal 3": {
      "file": "images/villa-fontaine-premier-haneda-airport-terminal-3.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Haneda Airport",
      "pageTitle": "Haneda Airport",
      "pageUrl": "https://en.wikipedia.org/wiki/Haneda_Airport"
    },
    "Shinagawa Station Tokyo": {
      "file": "images/shinagawa-station-tokyo.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Shinagawa Station",
      "pageTitle": "Shinagawa Station",
      "pageUrl": "https://en.wikipedia.org/wiki/Shinagawa_Station"
    },
    "Kyoto Station": {
      "file": "images/kyoto-station.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Kyōto Station",
      "pageTitle": "Kyōto Station",
      "pageUrl": "https://en.wikipedia.org/wiki/Ky%C5%8Dto_Station"
    },
    "Hotel Kyoto Shijo Kawaramachi": {
      "file": "images/hotel-kyoto-shijo-kawaramachi.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Kawaramachi Avenue",
      "pageTitle": "Kawaramachi Avenue",
      "pageUrl": "https://en.wikipedia.org/wiki/Kawaramachi_Avenue"
    },
    "Nishiki Market Kyoto": {
      "file": "images/nishiki-market-kyoto.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Nishiki Market",
      "pageTitle": "Nishiki Market",
      "pageUrl": "https://en.wikipedia.org/wiki/Nishiki_Market"
    },
    "Daishodo Woodblock Print Shop Kyoto": {
      "file": "images/daishodo-woodblock-print-shop-kyoto.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Nishiki Market",
      "pageTitle": "Nishiki Market",
      "pageUrl": "https://en.wikipedia.org/wiki/Nishiki_Market"
    },
    "Yamatake Senpo Kyoto": {
      "file": "images/yamatake-senpo-kyoto.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Nishiki Market",
      "pageTitle": "Nishiki Market",
      "pageUrl": "https://en.wikipedia.org/wiki/Nishiki_Market"
    },
    "Pontocho Alley Kyoto": {
      "file": "images/pontocho-alley-kyoto.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Ponto-chō",
      "pageTitle": "Ponto-chō",
      "pageUrl": "https://en.wikipedia.org/wiki/Ponto-ch%C5%8D"
    },
    "Gion Kyoto": {
      "file": "images/gion-kyoto.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Gion",
      "pageTitle": "Gion",
      "pageUrl": "https://en.wikipedia.org/wiki/Gion"
    },
    "Maruyama Park Kyoto": {
      "file": "images/maruyama-park-kyoto.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Yasaka Shrine",
      "pageTitle": "Yasaka Shrine",
      "pageUrl": "https://en.wikipedia.org/wiki/Yasaka_Shrine"
    },
    "Yasaka Pagoda Kyoto": {
      "file": "images/yasaka-pagoda-kyoto.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Yasaka Pagoda",
      "pageTitle": "Yasaka Pagoda",
      "pageUrl": "https://en.wikipedia.org/wiki/Yasaka_Pagoda"
    },
    "Hatsune Antiques Kyoto": {
      "file": "images/hatsune-antiques-kyoto.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Sannenzaka",
      "pageTitle": "Sannenzaka",
      "pageUrl": "https://en.wikipedia.org/wiki/Sannenzaka"
    },
    "Kiyomizu-dera Kyoto": {
      "file": "images/kiyomizu-dera-kyoto.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Kiyomizu-dera",
      "pageTitle": "Kiyomizu-dera",
      "pageUrl": "https://en.wikipedia.org/wiki/Kiyomizu-dera"
    },
    "Yogen-in Temple Kyoto": {
      "file": "images/yogen-in-temple-kyoto.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Tōfuku-ji",
      "pageTitle": "Tōfuku-ji",
      "pageUrl": "https://en.wikipedia.org/wiki/T%C5%8Dfuku-ji"
    },
    "Kamo River Kyoto": {
      "file": "images/kamo-river-kyoto.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Kamo River",
      "pageTitle": "Kamo River",
      "pageUrl": "https://en.wikipedia.org/wiki/Kamo_River"
    },
    "Kyoto": {
      "file": "images/kyoto.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Kyoto",
      "pageTitle": "Kyoto",
      "pageUrl": "https://en.wikipedia.org/wiki/Kyoto"
    },
    "Amanohashidate Station": {
      "file": "images/amanohashidate-station.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Amanohashidate",
      "pageTitle": "Amanohashidate",
      "pageUrl": "https://en.wikipedia.org/wiki/Amanohashidate"
    },
    "Seafood Atelier Hashidate Produce": {
      "file": "images/seafood-atelier-hashidate-produce.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Amanohashidate",
      "pageTitle": "Amanohashidate",
      "pageUrl": "https://en.wikipedia.org/wiki/Amanohashidate"
    },
    "Amanohashidate Viewland": {
      "file": "images/amanohashidate-viewland.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Amanohashidate",
      "pageTitle": "Amanohashidate",
      "pageUrl": "https://en.wikipedia.org/wiki/Amanohashidate"
    },
    "Amanohashidate sandbar": {
      "file": "images/amanohashidate-sandbar.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Amanohashidate",
      "pageTitle": "Amanohashidate",
      "pageUrl": "https://en.wikipedia.org/wiki/Amanohashidate"
    },
    "Amanohashidate seafood": {
      "file": "images/amanohashidate-seafood.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Amanohashidate",
      "pageTitle": "Amanohashidate",
      "pageUrl": "https://en.wikipedia.org/wiki/Amanohashidate"
    },
    "Nachi Falls": {
      "file": "images/nachi-falls.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Nachi Falls",
      "pageTitle": "Nachi Falls",
      "pageUrl": "https://en.wikipedia.org/wiki/Nachi_Falls"
    },
    "Tokyo Station": {
      "file": "images/tokyo-station.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Tokyo Station",
      "pageTitle": "Tokyo Station",
      "pageUrl": "https://en.wikipedia.org/wiki/Tokyo_Station"
    },
    "Koko Hotel Ginza 1-chome": {
      "file": "images/koko-hotel-ginza-1-chome.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Ginza",
      "pageTitle": "Ginza",
      "pageUrl": "https://en.wikipedia.org/wiki/Ginza"
    },
    "Akihabara Tokyo": {
      "file": "images/akihabara-tokyo.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Akihabara",
      "pageTitle": "Akihabara",
      "pageUrl": "https://en.wikipedia.org/wiki/Akihabara"
    },
    "Kappabashi Tokyo": {
      "file": "images/kappabashi-tokyo.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Kappabashi-dori",
      "pageTitle": "Kappabashi-dori",
      "pageUrl": "https://en.wikipedia.org/wiki/Kappabashi-dori"
    },
    "Seive Matcha Tokyo": {
      "file": "images/seive-matcha-tokyo.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Matcha",
      "pageTitle": "Matcha",
      "pageUrl": "https://en.wikipedia.org/wiki/Matcha"
    },
    "Kagetsudo Melon Bread Asakusa": {
      "file": "images/kagetsudo-melon-bread-asakusa.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Asakusa",
      "pageTitle": "Asakusa",
      "pageUrl": "https://en.wikipedia.org/wiki/Asakusa"
    },
    "Zaku Knives Tokyo": {
      "file": "images/zaku-knives-tokyo.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Kappabashi-dori",
      "pageTitle": "Kappabashi-dori",
      "pageUrl": "https://en.wikipedia.org/wiki/Kappabashi-dori"
    },
    "Kimono Reborn Tokyo": {
      "file": "images/kimono-reborn-tokyo.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Kimono",
      "pageTitle": "Kimono",
      "pageUrl": "https://en.wikipedia.org/wiki/Kimono"
    },
    "Tokyo Origami Museum": {
      "file": "images/tokyo-origami-museum.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Origami",
      "pageTitle": "Origami",
      "pageUrl": "https://en.wikipedia.org/wiki/Origami"
    },
    "Tokyo Skytree": {
      "file": "images/tokyo-skytree.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Tokyo Skytree",
      "pageTitle": "Tokyo Skytree",
      "pageUrl": "https://en.wikipedia.org/wiki/Tokyo_Skytree"
    },
    "Parazzo San Gusto Tokyo": {
      "file": "images/parazzo-san-gusto-tokyo.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Ginza",
      "pageTitle": "Ginza",
      "pageUrl": "https://en.wikipedia.org/wiki/Ginza"
    },
    "Imperial Palace Tokyo": {
      "file": "images/imperial-palace-tokyo.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Tokyo Imperial Palace",
      "pageTitle": "Tokyo Imperial Palace",
      "pageUrl": "https://en.wikipedia.org/wiki/Tokyo_Imperial_Palace"
    },
    "Samurai Museum Shinjuku": {
      "file": "images/samurai-museum-shinjuku.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Shinjuku",
      "pageTitle": "Shinjuku",
      "pageUrl": "https://en.wikipedia.org/wiki/Shinjuku"
    },
    "Godzilla Head Shinjuku": {
      "file": "images/godzilla-head-shinjuku.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Godzilla Street",
      "pageTitle": "Godzilla Street",
      "pageUrl": "https://en.wikipedia.org/wiki/Godzilla_Street"
    },
    "Tokyo Used Camera": {
      "file": "images/tokyo-used-camera.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Shinjuku",
      "pageTitle": "Shinjuku",
      "pageUrl": "https://en.wikipedia.org/wiki/Shinjuku"
    },
    "Tacos 3 Hermanos Tokyo": {
      "file": "images/tacos-3-hermanos-tokyo.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Shinjuku",
      "pageTitle": "Shinjuku",
      "pageUrl": "https://en.wikipedia.org/wiki/Shinjuku"
    },
    "Iyoshi Cola Tokyo": {
      "file": "images/iyoshi-cola-tokyo.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Shinjuku",
      "pageTitle": "Shinjuku",
      "pageUrl": "https://en.wikipedia.org/wiki/Shinjuku"
    },
    "Don Quijote Mega Shinjuku": {
      "file": "images/don-quijote-mega-shinjuku.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Don Quijote (store)",
      "pageTitle": "Don Quijote (store)",
      "pageUrl": "https://en.wikipedia.org/wiki/Don_Quijote_(store)"
    },
    "Shojin Tokyo ramen": {
      "file": "images/shojin-tokyo-ramen.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Ramen",
      "pageTitle": "Ramen",
      "pageUrl": "https://en.wikipedia.org/wiki/Ramen"
    },
    "Shibuya Hikarie Sky Lobby": {
      "file": "images/shibuya-hikarie-sky-lobby.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Shibuya Hikarie",
      "pageTitle": "Shibuya Hikarie",
      "pageUrl": "https://en.wikipedia.org/wiki/Shibuya_Hikarie"
    },
    "Enoshima Station Shonan Monorail": {
      "file": "images/enoshima-station-shonan-monorail.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Enoshima",
      "pageTitle": "Enoshima",
      "pageUrl": "https://en.wikipedia.org/wiki/Enoshima"
    },
    "Enoshima Iwaya Cave": {
      "file": "images/enoshima-iwaya-cave.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Enoshima",
      "pageTitle": "Enoshima",
      "pageUrl": "https://en.wikipedia.org/wiki/Enoshima"
    },
    "Enoshima Electric Railway": {
      "file": "images/enoshima-electric-railway.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Enoshima Electric Railway",
      "pageTitle": "Enoshima Electric Railway",
      "pageUrl": "https://en.wikipedia.org/wiki/Enoshima_Electric_Railway"
    },
    "Sasuke Inari Shrine Kamakura": {
      "file": "images/sasuke-inari-shrine-kamakura.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Sasuke Inari Shrine",
      "pageTitle": "Sasuke Inari Shrine",
      "pageUrl": "https://en.wikipedia.org/wiki/Sasuke_Inari_Shrine"
    },
    "Haneda Airport": {
      "file": "images/haneda-airport.jpg",
      "source": "wikimedia",
      "credit": "Wikipedia / Wikimedia Commons — Haneda Airport",
      "pageTitle": "Haneda Airport",
      "pageUrl": "https://en.wikipedia.org/wiki/Haneda_Airport"
    }
  }
};
